name: weather_now
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  geolocator: ^13.0.3
  weather: ^3.1.1
  intl: ^0.20.2
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  flutter_screenutil: ^5.9.3
  overlay_support: ^2.1.0
  google_fonts: ^6.2.1
  bloc: ^9.0.0
  meta: ^1.16.0
  geocoding: ^3.0.0
  lottie: ^3.3.1
  json_annotation: ^4.9.0
  auto_route: ^10.0.1
  dartz: ^0.10.1
  dio: ^5.8.0+1
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.6.1

  auto_route_generator: ^10.0.1
  build_runner: ^2.3.3



flutter:

  
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 700

  assets:
    - assets/images/
    - .env
